#pragma once

#define PR_MEMORY_ERROR 0
#define PR_INVALID_DATA_ERROR 1
#define PR_GL_ERROR 2

#define PR_LOG_LEVEL_FATAL 0
#define PR_LOG_LEVEL_ERROR 1
#define PR_LOG_LEVEL_WARNING 2
#define PR_LOG_LEVEL_INFO 3
#define PR_LOG_LEVEL_TRACE 4

#define PR_TEXTURE_SLOT_IMAGE 0
#define PR_TEXTURE_SLOT_SPECULAR_MAP 1

#define PR_TEXTURE_WRAPPING_REPEAT GL_REPEAT
#define PR_TEXTURE_WRAPPING_REPEAT_MIRRORED GL_MIRRORED_REPEAT
#define PR_TEXTURE_WRAPPING_EDGE GL_CLAMP_TO_EDGE
#define PR_TEXTURE_WRAPPING_COLOR GL_CLAMP_TO_BORDER
