#ifndef PR_TEXTURE_MULTISAMPLED_INTERNAL_H
#define PR_TEXTURE_MULTISAMPLED_INTERNAL_H

typedef struct prTextureMultisampledData prTextureMultisampledData;

void i_prTextureMultisampledCreateOnGPU(prTextureMultisampledData* texture);

void i_prTextureMultisampledDestroyOnGPU(prTextureMultisampledData* texture);

void i_prTextureMultisampledUpdateOnGPU(prTextureMultisampledData* texture);

#endif // PR_TEXTURE_MULTISAMPLED_INTERNAL_H
